name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip python3-venv \
          openjdk-11-jdk \
          git autoconf automake libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev \
          zip unzip

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install python-for-android
      run: |
        pip install --upgrade pip
        pip install python-for-android

    - name: Build APK with p4a
      run: |
        p4a apk \
          --requirements=python3,kivy==2.3.0,kivymd==1.2.0,plyer,yt-dlp,python-dateutil,urllib3 \
          --arch=arm64-v8a \
          --ndk-api=21 \
          --name="KivyApp" \
          --version=1.0 \
          --package=org.rameez.kivyapp \
          --private=$(pwd) \
          --android-api=33

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Kivy-APK
        path: *.apk